;;; flycheck-eldev-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flycheck-eldev.el

(autoload 'flycheck-eldev--initialize "flycheck-eldev")
(eval-after-load 'flycheck '(flycheck-eldev--initialize))
(register-definition-prefixes "flycheck-eldev" '("flycheck-eldev-"))

;;; End of scraped data

(provide 'flycheck-eldev-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flycheck-eldev-autoloads.el ends here
